image: maven:3-jdk-11

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - jdktests
  - mirroring

cache:
  paths:
  - .m2/repository/

build:
  stage: build
  script:
  - mvn compile

test:
  stage: test
  script:
  - mvn test

buildon12:
  image: maven:3-jdk-12
  stage: jdktests
  script:
    - mvn -e -X compile test -Djdk.version=12

buildon13:
  image: maven:3-jdk-13
  stage: jdktests
  script:
    - mvn -e -X compile test -Djdk.version=13

buildon14:
  image: maven:3-jdk-14
  stage: jdktests
  script:
    - mvn -e -X compile test -Djdk.version=14

buildon15:
  image: maven:3-adoptopenjdk-15
  stage: jdktests
  script:
    - mvn -e -X compile test -Djdk.version=15



github_mirroring:
  stage: mirroring
  script:
    - git push -f https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/si-codelounge/jsicko-tutorials.git HEAD:master
  only:
    - master
